services:
  postgres-nest:
    container_name: postgres-nest
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  task-management:
    container_name: task-management
    image: task-management:latest
    environment:
      DB_HOST: postgres-nest
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres-nest