apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management
  labels:
    app: task-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-management
  template:
    metadata:
      labels:
        app: task-management
    spec:
      containers:
      - name: task-management
        image: {{ .Values.image }}
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: {{ .Values.database.host }}
        - name: DB_PASSWORD
          value: {{ .Values.database.password }}

