apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management
  labels:
    app: task-management
spec:
    replicas: 1
    selector:
      matchLabels:
        app: task-management
    template:
        metadata:
            labels:
            app: task-management
        spec:
            containers:
            - name: task-management
            image: 
            ports:
            - containerPort: 3000
            env:
              - name: DB_HOST
                value: 
              - name: DB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: db-password
                    key: password