#############################################################
# Specifies when workflow will run
#############################################################

on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      types: [opened, synchronize, reopened]
  
env:
  IMAGE_NAME: task-management
  TAG: $(echo "${{ github.sha }}" | cut -c1-7)

#############################################################
# Specifies jobs to run
#############################################################

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Code Vulnerability Check
        uses: anchore/scan-action@v3
        id: scan-build
        with:  
          path: "${{ github.workspace }}"
          fail-build: true
          severity-cutoff: "high"
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan-build.outputs.sarif }}
      - name: Build OCI Image with Buildpacks
        uses: mamezou-tech/buildpacks-action@master
        with:
          builder: gcr.io/buildpacks/builder:latest
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ env.TAG }}
      - name: List Docker Images
        run: docker image ls
      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
      - name: Upload Trivy scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results.sarif